[tool.poetry]
name = "cardsort"
version = "0.1.0"
description = "Analyse cardsorting data"
authors = ["Katharina Kloppenborg"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
